name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Ensure that we have all history and all tags for git versioning
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install with maven
        run: mvn -B install
      - name: Export coverage information
        run: mvn jacoco:report -Dcode-coverage-format=xml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            target/Digital.zip
            target/docuDist/Doc_*.pdf
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
